name: Build Spring Boot

on:
  push:
    branches: [ "main" ]
    paths:
      - spring-boot/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bestrand/visitors

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: 17

      - run: echo "IMAGE_TAG=spring-boot-${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build image
        run: cd spring-boot && mvn spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
     
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push image'
        run:
          docker push ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
